version: '3'
services:
  kuldeep-mysql:
    container_name: kuldeep-mysql
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: test
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    restart: always

  app:
    build: .
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    working_dir: /app
    ports:
      - 9090:9090
    command: mvn clean spring-boot:run
    depends_on:
      - kuldeep-mysql